#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IOS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_ID="__UNI__B5780B0"
EXPECTED_RUNTIME_VERSION="5.25"
resource_manifest="$IOS_DIR/FocusPlanet/FocusPlanet/uni-app-x/apps/$APP_ID/www/manifest.json"

command -v xcodebuild >/dev/null || { echo "Xcode command-line tools are missing." >&2; exit 1; }
[[ -d "$IOS_DIR/SDK/Libs/DCloudUniappRuntime.xcframework" ]] || { echo "Missing SDK; run install-sdk.sh." >&2; exit 1; }
[[ -d "$IOS_DIR/CustomFrameworks/DCloudUTSExtAPI.xcframework" ]] || { echo "Missing custom DCloudUTSExtAPI; run build-extapi.sh." >&2; exit 1; }
[[ -f "$resource_manifest" ]] || { echo "Missing exported $APP_ID app resources; run sync-resources.sh." >&2; exit 1; }
[[ "$(cat "$IOS_DIR/SDK/.uniappx-sdk-version" 2>/dev/null || true)" == "$EXPECTED_RUNTIME_VERSION" ]] || { echo "Expected uni-app x iOS SDK $EXPECTED_RUNTIME_VERSION; run install-sdk.sh." >&2; exit 1; }
[[ "$(plutil -extract 'uni-app-x.compilerVersion' raw -o - "$resource_manifest" 2>/dev/null || true)" == "$EXPECTED_RUNTIME_VERSION" ]] || { echo "App resources were not generated by HBuilderX $EXPECTED_RUNTIME_VERSION; regenerate and sync them." >&2; exit 1; }
[[ "$(plutil -extract 'uniapp-x.uniRuntimeVersion' raw -o - "$IOS_DIR/FocusPlanet/FocusPlanet/Info.plist" 2>/dev/null || true)" == "$EXPECTED_RUNTIME_VERSION" ]] || { echo "Info.plist runtime version must be $EXPECTED_RUNTIME_VERSION." >&2; exit 1; }
[[ -f "$IOS_DIR/Plugins/unimoduleFocusFaceDetector.framework/unimoduleFocusFaceDetector" ]] || { echo "Missing face detector framework; run build-plugin.sh." >&2; exit 1; }

if rg -q 'INFOPLIST_KEY_UI(Main|Launch)Storyboard' "$IOS_DIR/FocusPlanet/FocusPlanet.xcodeproj/project.pbxproj"; then
  echo "The host declares a storyboard that is not bundled; remove the generated storyboard build settings." >&2
  exit 1
fi

if nm -gj "$IOS_DIR/Plugins/unimoduleFocusFaceDetector.framework/unimoduleFocusFaceDetector" | rg -q 'OBJC_CLASS_\$_(UTSOC|DCloudUTSConfig)'; then
  echo "The face detector contains duplicate UTS bootstrap classes; rebuild it without UTSOC.mm." >&2
  exit 1
fi
# 首页渐变已改为静态 SVG，不再要求原生渐变类；端侧检测仍保留完整校验。

plist_appid="$(/usr/libexec/PlistBuddy -c 'Print :uniapp-x:appid' "$IOS_DIR/FocusPlanet/FocusPlanet/Info.plist")"
[[ "$plist_appid" == "$APP_ID" ]] || { echo "Info.plist appid mismatch: $plist_appid" >&2; exit 1; }

"$SCRIPT_DIR/check-resource-freshness.sh"
xcodebuild -list -project "$IOS_DIR/FocusPlanet/FocusPlanet.xcodeproj" >/dev/null
echo "Xcode local-packaging inputs are ready."
